- name: Copy Config File
  ansible.builtin.template:
    src: job.xml
    dest: /tmp/job.xml

- name: Create a jenkins job
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/job.xml') }}"
    name: test
    url: http://172.31.90.201:8080  #private ip of jenkins
    user: admin
    password: "{{jenkins_password}}"
  loop:
    - frontend
    - catalogue
    - cart
