- name: Create Folder Config file
  ansible.builtin.template:
    src: folder.xml
    dest: /tmp/folder.xml


- name: Create Folder - "{{item.dir}}"
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/folder.xml') }}"
    name: "{{item.dir}}"
    url: http://172.31.90.201:8080
    user: admin
    password: "{{jenkins_password}}"

- name: Create Job Config file
  ansible.builtin.template:
    src: s-job.xml
    dest: /tmp/s-job.xml


- name: Create Job - "{{item.dir}}/{{item.name}}"
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/s-job.xml') }}"
    name: "{{item.dir}}/{{item.name}}"
    url: http://172.31.90.201:8080
    user: admin
    password: "{{jenkins_password}}"


